package gamevrf

import (
	"github.com/minio/blake2b-simd"
)

// VRFOut represents the output of a Verifiable Random Function (VRF)
type VRFOut struct {
	Height uint64 // Height of the block associated with the VRF output
	Proof  []byte // Proof generated by the VRF
}

// Sum256 computes a 32-byte hash (blake2b) of the VRF proof
func (vrf *VRFOut) Sum256() [32]byte {
	return blake2b.Sum256(vrf.Proof)
}
